version: '2'
linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: "sigs.k8s.io/cluster-api/.*" is deprecated: This package is deprecated and is going to be removed when support for v1beta1 will be dropped.'
        # Specific exclude rule for deprecated types that are still part of the codebase. These
        # should be removed as the referenced deprecated types are removed from the project.
