apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      app:
        appOperator:
          catalog: {{ .Values.appOperator.catalog }}
          version: {{ .Values.appOperator.version }}
        chartOperator:
          catalog: {{ .Values.chartOperator.catalog }}
          version: {{ .Values.chartOperator.version }}
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      provider:
        kind: {{ .Values.provider.kind }}
      proxy:
        noProxy: {{ .Values.proxy.noProxy }}
        http: {{ .Values.proxy.http }}
        https: {{ .Values.proxy.https }}
      workload:
        cluster:
          baseDomain: '{{ .Values.baseDomain }}'
          calico:
            subnet: '{{ .Values.cni.subnet }}'
            cidr: '{{ .Values.cni.mask }}'
          kubernetes:
            api:
              clusterIPRange: '{{ .Values.kubernetes.api.clusterIPRange }}'
            domain: '{{ .Values.kubernetes.clusterDomain }}'
          owner: '{{ .Values.managementClusterID }}'
