version: 2.1

orbs:
  architect: giantswarm/architect@4.31.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: cluster-apps-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-cluster-apps-operator-to-docker
          image: "docker.io/giantswarm/cluster-apps-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-cluster-apps-operator-to-quay
          image: "quay.io/giantswarm/cluster-apps-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-cluster-apps-operator-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/cluster-apps-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/


      - architect/push-to-app-catalog:
          context: "architect"
          name: push-cluster-apps-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-apps-operator"
          requires:
            - push-cluster-apps-operator-to-docker
            - push-cluster-apps-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: "basic-integration-test"
          install-app-platform: true
          test-dir: "integration/test/basic"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog

      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-aws-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-capa-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-gcp-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-vsphere-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-cloud-director-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cluster-apps-operator-to-capz-app-collection
          app_name: "cluster-apps-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-cluster-apps-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
